version: "3.9"

services:
  app:
    build: .
    restart: unless-stopped
    env_file:
      - .env
    environment:
      DATABASE_URL: "sqlite+aiosqlite:///./raksh.db"
    volumes:
      - ./logs:/app/logs
      - raksh_data:/app
    ports:
      - "8000:8000"

volumes:
  raksh_data:
